### ISSUE TITLE
Dimension Mismatch in turtle_super_t1_arch

### ISSUE THREAD

**Issue by hamidreza07** [Ascend-Research/Turtle#2]
During the training of the super-resolution model in `turtle_super_t1_arch`, I encountered a dimension mismatch error in the `forward` method when calculating the `ending` output. Specifically, the line:

```python
ending = self.ending(out_dec_level1) + current
```

triggers the following error:
```
RuntimeError: The size of tensor a (192) must match the size of tensor b (48) at non-singleton dimension 3
```

**Error Details**:
- **`self.ending(out_dec_level1)` shape**: `[1, 3, 192, 192]`
- **`current` shape**: `[1, 3, 48, 48]`

The `self.ending(out_dec_level1)` tensor has dimensions `(192, 192)` for height and width, while `current` has dimensions `(48, 48)`. This mismatch prevents addition and causes the runtime error.

**Comment by Amirhosein-gh98** [comment]
Hi,

Thank you for highlighting this issue. 
I have corrected it by ensuring that the input frames are upsampled before the addition. 

Please let us know if you encounter any further issues.

**Comment by hamidreza07** [comment]
### Process Killed During Inference in `encoder_level3` and in `transformer_blocks`

I’d also like to thank you for the support and the model, which has been very valuable in my work on super-resolution tasks.

**Description**:  
While running inference with the `turtle_super_t1_arch` model, the process is unexpectedly killed during the execution of `encoder_level3`. The issue arises after loading the model and beginning inference.

**Error Details**:
- **Stage**: `encoder_level3` layer in the model
- **Symptom**: The process terminates without an explicit error message.

**Comment by Amirhosein-gh98** [comment]
Thank you! Glad to hear that our work has been helpful to you.

Are you sure you’re not running out of memory? If you have memory limitations, consider reducing the patch size or overlap size in the inference code. Also in the load_model function, you need to select between cpu and gpu.

**Comment by hamidreza07** [comment]
Thank you! Before your modification, I made some adjustments myself, but I'm not completely sure about them. I'll train on my data again with your modification, and if I encounter any issues, I'll reach out to let you know. Thanks again for your support!

**Comment by Amirhosein-gh98** [comment]
Good luck!
