### ISSUE TITLE
Missing Downsampling in inference_no_ground_truth.py Causes Mismatch Error

### ISSUE THREAD

**Issue by hamidreza07** [Ascend-Research/Turtle#4]
In the `inference_no_ground_truth.py` script, the code does not include the downsampling step for `in_patch_prev` and `in_patch_curr` using `torch.nn.functional.interpolate`. This omission leads to a mismatch error when running the super-resolution model, as the model expects inputs at a specific scale.

The missing code:
```python
in_patch_prev = torch.nn.functional.interpolate(in_patch_prev, 
                                                scale_factor=1/4, 
                                                mode="bicubic")
in_patch_curr = torch.nn.functional.interpolate(in_patch_curr, 
                                                scale_factor=1/4, 
                                                mode="bicubic")
```

#### Problem
The mismatch error occurs because the input patches are not downscaled as required by the super-resolution model. This issue is handled correctly in `inference.py`, but the same logic is missing in `inference_no_ground_truth.py`.

#### Proposed Fix
Add the following lines in the `inference_no_ground_truth.py` script where patches `in_patch_prev` and `in_patch_curr` are defined:
```python
in_patch_prev = torch.nn.functional.interpolate(in_patch_prev, 
                                                scale_factor=1/4, 
                                                mode="bicubic")
in_patch_curr = torch.nn.functional.interpolate(in_patch_curr, 
                                                scale_factor=1/4, 
                                                mode="bicubic")
```

This change will prevent the mismatch error and align the preprocessing steps in `inference_no_ground_truth.py` with those in `inference.py`.

**Comment by Amirhosein-gh98** [comment]
Hi,

Thanks for raising the issue and pointing out the problem in detail. The bug is fixed now.
